General:
  ConfigurationVersion: 2
  MinRefineryVersion: v2.0

Specialized:
  UseRegexForFieldsToPropagateFromRoot: false
  FieldsToPropagateFromRoot:
    - foo

GRPCServerParameters:
  Enabled: true
  ListenAddr: 0.0.0.0:4317