services:
  refinery:
    image: ko.local/refinery:latest # build this with 'make local_image' at the root of the repo
    pull_policy: never # 'Error response from daemon: No such image' means you need to build it. 👆
    environment: # these take precedence over the settings in env_file
      REFINERY_REDIS_HOST: redis:6379
    volumes:
      - ./config.yaml:/etc/refinery/refinery.yaml
      - ./rules.yaml:/etc/refinery/rules.yaml
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:9090:9090
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7
    command: "redis-server"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 2s
      timeout: 3s
      retries: 5
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis-data:/data

  healthcheck:
    image: curlimages/curl:latest
    depends_on:
      - refinery
      - redis
    command: >
      sh -c "
      echo 'Waiting for Refinery to be ready...';
      for i in $$(seq 1 30); do
        if curl -f -s http://refinery:8080/ready > /dev/null 2>&1; then
          echo 'SUCCESS: Refinery is ready!';
          exit 0;
        fi;
        echo \"Attempt $$i/30: Refinery not ready yet, retrying in 2s...\";
        sleep 2;
      done;
      echo 'FAILED: Refinery did not become ready in time';
      exit 1
      "

volumes:
  redis-data:
