name: Add to project
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    name: Add issues and PRs to project
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/honeycombio/projects/11
          github-token: ${{ secrets.GHPROJECTS_TOKEN }}
